nginx:
  build: ./nginx
  ports: 
    - "4000:80"
  links:
    - "app1:app1"
    - "app2:app2"
    - "app3:app3"

app1:
  build: ./app
  volumes:
    - ./app:/app
  ports:
    - "4000"
  links:
    - "redis"

app2:
  build: ./app
  volumes:
    - ./app:/app
  ports:
    - "4000"
  links:
    - "redis"

app3:
  build: ./app
  volumes:
    - ./app:/app
  ports:
    - "4000"
  links:
    - "redis"

redis:
  build: ./redis
  ports: 
    - "6379"
